### PR TITLE
Harpy Gaiden (Pocket Edition) Keymaps

### PR DESCRIPTION
**Pull request by SofyUchiha**
Harpy Gaiden Pocket Edition is a fine-tuned version made specially for smartphones.

### CODE REVIEW

**Comment by Rinnegatamante** [comment]
The name file lacks .ini

**Comment by SofyUchiha** [comment]
Sorry! Fixed.

**Comment by Rinnegatamante** [comment]
Does that game have a report in the compatibility list? I can't find any game with that game id.

**Comment by SofyUchiha** [comment]
yep, only that in this issue the pocket version was reported first and I think it was confused with the pc version. Anyway the ID of this game is: [Harpy Gaiden Pocket Edition]
https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/87

**Comment by Rinnegatamante** [comment]
Create a new report for the pcket edition. Also the ini file is full maiusc. Is the game id like that? If not, filename must be adjusted.

**Comment by SofyUchiha** [comment]
Done! https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/issues/293

**Pull request merged**
